### ISSUE TITLE
[Question] does the controller continually perform a refresh-then-update on the stacks it manages? 

### ISSUE THREAD

**Issue by gunniwho** [pulumi/pulumi-kubernetes-operator#120]
Or does it just `pulumi up` the stack once and then forget about it (until it needs to destroy it)?

**Comment by leezen** [comment]
This is controlled via the parameters you pass to the stack CR: https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/deploy/crds/pulumi.com_stacks.yaml#L74

**Comment by gunniwho** [comment]
Thank you @leezen for your response. I understand that setting the refresh config value to true will result in the stack being refreshed before it's updated. My question is whether the stack is _continually_ updated by the controller and thus maintaining the desired state, regardless of (undesired) changes to the stack's resources by an external party. Thanks again!

**Comment by viveklak** [comment]
@gunniwho no - the operator is currently implemented to drive the desired state of a "stack" CR. It will trigger if the stack CR's state is updated and continue to drive it till success. Once the desired state is reached, the next trigger would really only be when the stack CR state changes or is deleted.

**Comment by gunniwho** [comment]
Thanks @viveklak. Am I correct to assume then that if I were to provide a mechanism to continually "touch" the stack CR (say every minute for example) together with using the refresh option, that would make the controller continually maintain the desired state of the stack's resources, including reverting undesired changes by an external party?

**Comment by viveklak** [comment]
@gunniwho in theory yes but we haven't put the controller through that use case. Would be curious to hear about your experience if you did go down that path.

I'd recommend trying at a cadence of 5-ish minutes to begin with since the applies are somewhat heavyweight right now. 

Also you will have to actually change the spec of the CR due to the predicates in use: https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/pkg/controller/stack/stack_controller.go#L89. Alternatively you could try adding `predicate.AnnotationChangedPredicate{}` to the predicate Or statement at the line above to allow you to touch an annotation to tickle the controller instead.

**Comment by gunniwho** [comment]
Thanks for the info @viveklak! I will post if and when I give this a shot.

**Comment by prometherion** [comment]
> Am I correct to assume then that if I were to provide a mechanism to continually "touch" the stack CR (say every minute for example) together with using the refresh option, that would make the controller continually maintain the desired state of the stack's resources

Or what about putting an additional key to the CRD as `refreshTimeout *time.Duration` and using the [`RequeAfter`](https://github.com/kubernetes-sigs/controller-runtime/blob/ce2f0c92d77e05609fab003663f2b5bb9c1990d7/pkg/reconcile/reconcile.go#L31-L33) (along with [`Requeue`](https://github.com/kubernetes-sigs/controller-runtime/blob/ce2f0c92d77e05609fab003663f2b5bb9c1990d7/pkg/reconcile/reconcile.go#L28-L29) to true) struct field to the reconcile request object, so the Operator can refresh the desired state?

I think it's a more neat implementation rather than _touching_ a resource.
