### ISSUE TITLE
Deploy the operator using a Helm chart

### ISSUE THREAD

**Issue by adace123** [pulumi/pulumi-kubernetes-operator#260]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Having the option to deploy the operator via a Helm chart would be very convenient for my project setup, which will make extensive use of Helm charts.

### Affected area/feature
K8S Operator

**Comment by adace123** [comment]
Thanks for the reply @viveklak . I'd be happy to give it a try 👍

**Comment by rockhowse** [comment]
@adace123 and @viveklak thank you both for looking into this issue. 😄 It looks like this PR is waiting on a potential merge conflict resolution and final acceptance/merge. 

We are currently evaluating the usage of `pulumi` for our IaC solution and given that this uses the `kubernetes-operator` pattern, we are super enthusiastic to dive in. I would highly encourage expediting the final evaluation and merging of this PR as deployment of things like operators using helm is becoming more ubiquitous and will drive adoption. 

For our specific use case, we are leveraging gitops usingthe [flux](https://fluxcd.io/). In order to make helm based k8s deployments a first class citizen, flux includes a key component called a [HelmRelease](https://fluxcd.io/docs/components/helm/helmreleases/) which supports a GitRepository as a source, but currently requires a helm chart be available in the repository. 

Until this PR gets merged, we are going to have to copy the CRD and Deployment artifacts directly into our own repo and inject it directly using a kustomization. Or, alternatively we can fork the repo and make use of the code in the PR until the code has officially been merged. If there is anything we can do to help test or contribute to expedite the adoption of this feature feel free to reach out.

**Comment by EronWright** [comment]
Good news everyone, we just released a preview of Pulumi Kubernetes Operator v2. This new release has a whole-new architecture that uses pods as the execution environment. We now provide a Helm chart and other installation options.

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/). 
cc @adace123 @sudermanjr @questionmorc @rockhowse @pelumi1163 @worawatwi
