### ISSUE TITLE
Mechanism to refresh dynamic credentials for providers

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes-operator#299]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
In many production scenarios, cloud provider credentials may be retrieved from external entities like Vault. Refresh doesn't instantiate the pulumi program and providers are instantiated from state which might mean using stale credentials if the dynamism is encoded in the Pulumi program. CLI users have mechanisms such as https://github.com/pulumi/pulumi/issues/4981#issuecomment-655881330 to workaround this but this is not supported in autonomous systems like the Operator. This prevents operator users from using mechanisms like auto-refresh added in https://github.com/pulumi/pulumi/pull/8071 for their stacks and might require manual intervention for refreshing credentials.

Approaches discussed so far are to add support one of the following in the stack specification:
1. Support a pre-flight script which can be used to fetch credentials from external entities and populate things like files, environment variables etc. supported by the underlying cloud provider. 
2. Support a mechanism to allow stack authors to selectively target specific URNs for update before running refresh. This is essentially the equivalent of running `pulumi up -t <provider>` as in the CLI workaround mentioned above. With this the credential refresh code could live within the pulumi program and leverage the pulumi sdk instead of in a hand-coded script.

**Comment by squaremo** [comment]
Some additional qualifications:

 - this is an issue with first-class providers specifically, because the problem arises when you explicitly construct a provider in order to do further work; since a constructed provider is a resource, its inputs are captured in the stack.
 - any solution must account for multiple "hops"; that is, must work when a provider is used to construct another provider. 

**Pre-flight script**

If this is an arbitrary shell script, you have to make sure the container image has all the executables that might be invoked in the script. That's API clients for all the cloud platforms, clients for other tooling like Vault. The list is endless, so in practice is means some combination of dumping things in the released container image to cover the 80% needs, and people having to construct their own bespoke images.

**Targeted `pulumi up`**

I would expect this to put some restrictions on the way the program is written (and I would love to understand in detail what they are! :-)

If it is onerous to write a program which serves for `pulumi up -r` as well as `pulumi -t` for providers, perhaps it would be better to have two separate programs, one for doing provider construction, and one for using the providers; and a mechanism for making the latter program depend on the former.

**Comment by squaremo** [comment]
I think using `pulumi up -t` is the more conservative change, so all else being equal, I would go for that one.
