### ISSUE TITLE
PKO v2 Migration guide

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-kubernetes-operator#633]
Document any steps needed, and differences to be aware of for users to adopt the new PKO resources

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
Key points (WIP):
- cross-namespace references are strictly disallowed

**Comment by blampe** [comment]
* Git auth needs to be specified as secret refs
* Adding SSH known hosts → layer them into the container

**Comment by EronWright** [comment]
More draft material:

## What's Changed

- The Operator is natively multi-tenant and can only be installed cluster-wide, not on a per-namespace basis.
- Each stack runs in a separate pod in the Stack object's namespace.  These pods are known as _workspace pods_.
- The workspace pod runs with a 'restricted' (low-privilege) security profile.
- The workspace pod stays running after the update has been applied, with minimal resource usage.  It runs with a burstable class-of-service by default.
- Your Stack uses the pod's ServiceAccount to authenticate to the Kubernetes API.  Previously, the Operator's own ServiceAccount served as the identity.
- When a Stack configuration setting or other spec element is changed, the stack is updated.  Previously, stack updates occurred only due to source code changes.
- New customization points:  It is now possible to mount volumes, init containers, and sidecars to a stack's pod.

## Migration

1. Create a ServiceAccount for your stack.
2. Grant the `system:auth-delegator` ClusterRole to the ServiceAccount, using a ClusterRoleBinding.
3. Ensure that you aren't using cross-namespace references, e.g. for secret references or for stack dependencies.
4. Ensure that you aren't using "file" refs.
5. If using Flux sources, install the provided Network Policy to allow the workspace pod to access the Flux source controller.

**Comment by EronWright** [comment]
Handled in #657
